const assert=require('assert');
const fs=require('fs');
const path=require('path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script[^>]+src="https:[^"]+"[^>]*><\/script>/g,'').replace(/<script src="src\/[^"]+"><\/script>/g,'');
const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
w.alert=msg=>{throw new Error(`Unexpected alert: ${msg}`)};
w.HTMLCanvasElement.prototype.getContext=function(){return new Proxy({},{get:(t,p)=>p==='measureText'?(()=>({width:10})):(p==='canvas'?this:(()=>{})),set:(t,p,v)=>true})};
const scripts=['src/state.js','src/app.js','src/analysis.js','src/v05.js','src/ai-analytics.js','src/relationship-stats.js','src/data-profile.js','src/journey.js'];
w.eval(scripts.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n;\n'));
w.document.dispatchEvent(new w.Event('DOMContentLoaded',{bubbles:true}));
const tick=()=>new Promise(r=>w.setTimeout(r,0));
(async()=>{
  w.demo();await tick();
  assert.strictEqual(w.document.getElementById('rows').textContent,'9');
  assert.ok(w.document.getElementById('startDatasetBand').classList.contains('show'),'loaded dataset band should show');
  const profileButton=w.document.querySelector('[data-journey-step="profile"]');
  assert.strictEqual(profileButton.disabled,false,'Data Profile should unlock after dataset load');
  w.goToJourneyStep('profile');await tick();
  assert.ok(!w.document.getElementById('variablesView').classList.contains('hidden'),'Step 2 should render');
  assert.strictEqual(w.document.getElementById('profileRows').textContent,'9');
  assert.ok(w.document.getElementById('profileOverview').textContent.includes('Field structure'));
  w.setProfileTab('quality');
  assert.ok(w.document.querySelector('[data-profile-pane="quality"]').classList.contains('active'));
  assert.ok(w.document.getElementById('profileQuality').textContent.includes('Cell completeness'));
  w.setProfileTab('relationships');
  const a=w.document.getElementById('relFieldA'),b=w.document.getElementById('relFieldB');
  a.value='Score';b.value='Age';w.updateProfileRelationshipMethod();w.runProfileRelationship();
  assert.ok(w.document.getElementById('relationshipResult').textContent.includes('Pearson r'),'Scale↔Scale should route to correlation');
  a.value='Group';b.value='Score';w.updateProfileRelationshipMethod();w.runProfileRelationship();
  assert.ok(w.document.getElementById('relationshipResult').textContent.includes('eta squared'),'Scale↔categorical should route to eta squared');
  a.value='Group';b.value='Satisfaction';w.updateProfileRelationshipMethod();w.runProfileRelationship();
  assert.ok(w.document.getElementById('relationshipResult').textContent.includes('Cramér'),'categorical↔categorical should route to Cramér’s V');
  w.clearAll();await tick();
  assert.ok(!w.document.getElementById('startDatasetBand').classList.contains('show'),'dataset band should hide after clear');
  console.log('FRONTEND_DOM_SMOKE_OK');
})().catch(err=>{console.error(err);process.exit(1)});
