const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),css=read('src/landing.css');
const jsFiles=['src/landing-copy.js','src/landing-content.js','src/landing.js'];
const js=jsFiles.map(read).join('\n');
const ok=(x,m)=>{if(!x)throw Error(m)};
ok(fs.existsSync(path.join(root,'app.html')),'Canonical Product app.html must exist');
ok(html.includes('href="app.html"'),'CTA must target app.html');
for(const p of ['src/landing.css',...jsFiles]) ok(html.includes(p),'Missing landing dependency '+p);
ok(!/(href|src)=["']\/(?!\/)/.test(html),'Root-absolute authored path found');
for(const x of ['src/app.js','src/app.css','src/ai-analytics.js','src/state.js','src/journey.js','/analyze']) ok(!html.includes(x)&&!js.includes(x),'Functional dependency: '+x);
for(const x of ['KU_Logo_AI.svg','KU_Logo_Accent_Color.svg','KU_Logo_White_Transparent.svg']) ok(fs.existsSync(path.join(root,'assets/landing/brand',x)),'Missing '+x);
ok(css.includes('.motion-ready .reveal'),'Reveal fail-safe missing');
ok(css.includes('@media(max-width:1050px)'),'Tablet breakpoint missing');
ok(css.includes('@media(max-width:700px)'),'Mobile breakpoint missing');
ok(js.includes("localStorage.getItem('ku-open-da-lang')"),'Language preference persistence missing');
ok(js.includes('ใช้ข้อมูลให้ตัดสินใจได้ดีขึ้น'),'Natural Thai copy missing');
ok(!js.includes('fetch(')&&!js.includes('XMLHttpRequest'),'Landing must not call APIs');
ok(!html.includes('id="workspaceView"'),'Public Landing must not contain Product workspace shell');
console.log('[landing_smoke] PASS (index.html → app.html)');
