// KU Open DA — production Step 1/2 controller. Uses the functional dataset state in app.js.
(function(){
'use strict';
const el=id=>document.getElementById(id);
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(v,d=3)=>Number.isFinite(v)?Number(v).toFixed(d):'—';
const pct=v=>Number.isFinite(v)?`${(100*v).toFixed(1)}%`:'—';
const stats=()=>window.KURelationshipStats;
function loaded(){return typeof headers!=='undefined'&&typeof data!=='undefined'&&headers.length>0&&data.length>0}
function datasetName(){const context=window.KUDataLoader?.getContext?.();if(context?.name)return context.name;const f=el('file')?.files?.[0];if(f?.name)return f.name;return el('paste')?.value?.trim()?'Pasted / demo dataset':'Current dataset'}
function missingCount(){if(!loaded())return 0;let n=0;for(const r of data)for(const h of headers)if(r[h]===''||r[h]===null||r[h]===undefined)n++;return n}
function duplicateRows(){if(!loaded())return 0;const seen=new Set();let dup=0;for(const r of data){const key=headers.map(h=>String(r[h]??'')).join('\u001f');if(seen.has(key))dup++;else seen.add(key)}return dup}
function fieldSummary(h){const vals=data.map(r=>r[h]).filter(v=>v!==''&&v!==null&&v!==undefined),missing=data.length-vals.length,unique=new Set(vals.map(String)).size;return{name:h,storage:types[h],level:meta[h]?.level||'Nominal',n:vals.length,missing,unique,missingRate:missing/Math.max(1,data.length)}}
function summaries(){return loaded()?headers.map(fieldSummary):[]}
function fieldKind(h){return types[h]==='numeric'&&meta[h]?.level==='Scale'?'numeric':'categorical'}
function updateStart(){const band=el('startDatasetBand');if(!band)return;if(!loaded()){band.classList.remove('show');return}const miss=missingCount();band.classList.add('show');band.innerHTML=`<div><div class="dataset-context-name">${safe(datasetName())}</div><div class="dataset-context-meta"><span class="context-pill">${data.length.toLocaleString()} rows</span><span class="context-pill">${headers.length} fields</span><span class="context-pill">${miss.toLocaleString()} missing cells</span></div></div><button class="btn secondary" onclick="goToJourneyStep('profile')">Open Data Profile →</button>`}
function signal(title,count,detail,warn){return `<div class="profile-signal${warn?' warn':''}"><b>${safe(title)} · ${count}</b><span>${safe(detail)}</span></div>`}
function renderOverview(){const host=el('profileOverview');if(!host||!loaded())return;const ss=summaries(),counts={Scale:0,Ordinal:0,Nominal:0};ss.forEach(s=>counts[s.level]=(counts[s.level]||0)+1);const max=Math.max(1,...Object.values(counts)),identifiers=ss.filter(s=>s.n>0&&s.unique===s.n&&s.n>=10),highMissing=ss.filter(s=>s.missingRate>=.2),constants=ss.filter(s=>s.unique<=1);host.innerHTML=`<div class="profile-overview-grid"><section class="card"><div class="head">Field structure</div><div class="body"><div class="field-type-list">${Object.entries(counts).map(([k,v])=>`<div class="field-type-row"><b>${k}</b><div class="field-type-track"><span style="width:${100*v/max}%"></span></div><span>${v}</span></div>`).join('')}</div><div class="note" style="margin-top:12px">Measurement level drives method selection. Scale fields are treated as numeric relationships; Nominal/Ordinal fields are treated as categorical in the relationship explorer.</div></div></section><section class="card"><div class="head">Signals to review</div><div class="body"><div class="profile-signal-list">${signal('Potential identifiers',identifiers.length,identifiers.slice(0,5).map(x=>x.name).join(', ')||'None detected',false)}${signal('High missingness fields',highMissing.length,highMissing.slice(0,5).map(x=>`${x.name} (${pct(x.missingRate)})`).join(', ')||'None at or above 20%',highMissing.length>0)}${signal('Constant / empty fields',constants.length,constants.slice(0,5).map(x=>x.name).join(', ')||'None detected',constants.length>0)}</div></div></section></div>`}
function renderQuality(){const host=el('profileQuality');if(!host||!loaded())return;const ss=summaries(),miss=missingCount(),total=data.length*headers.length,dup=duplicateRows(),constants=ss.filter(s=>s.unique<=1),highMissing=ss.filter(s=>s.missingRate>=.2),completeness=1-miss/Math.max(1,total),issues=[];issues.push(miss?['Missing values',`${miss.toLocaleString()} cells are missing across ${ss.filter(s=>s.missing>0).length} fields.`,'review']:['Missing values','No missing cells detected.','ok']);issues.push(dup?['Duplicate rows',`${dup.toLocaleString()} duplicate row(s) detected using all current fields.`,'review']:['Duplicate rows','No exact duplicate rows detected.','ok']);issues.push(constants.length?['Constant / empty fields',`${constants.length} field(s) have one or zero observed values: ${constants.slice(0,6).map(s=>s.name).join(', ')}.`,'review']:['Constant / empty fields','No constant or empty fields detected.','ok']);if(highMissing.length)issues.push(['High missingness',`${highMissing.length} field(s) are at least 20% missing.`,'review']);host.innerHTML=`<div class="quality-grid"><div class="quality-card"><b>${pct(completeness)}</b><span>Cell completeness</span></div><div class="quality-card"><b>${miss.toLocaleString()}</b><span>Missing cells</span></div><div class="quality-card"><b>${dup.toLocaleString()}</b><span>Exact duplicate rows</span></div><div class="quality-card"><b>${constants.length}</b><span>Constant / empty fields</span></div></div><div class="quality-issues">${issues.map(([a,b,c])=>`<div class="quality-issue"><div><b>${safe(a)}</b><span>${safe(b)}</span></div><span class="issue-badge${c==='review'?' review':''}">${c==='review'?'Needs review':'OK'}</span></div>`).join('')}</div><div class="note" style="margin-top:10px">These are descriptive data-quality checks, not a universal quality score. Whether an issue requires correction depends on the analytical question.</div>`}
function renderProfileHeader(){if(!loaded())return;const miss=missingCount(),numeric=headers.filter(h=>fieldKind(h)==='numeric').length,band=el('profileDatasetBand');if(band)band.innerHTML=`<div><b>${safe(datasetName())}</b><span>${data.length.toLocaleString()} rows × ${headers.length} fields · ${miss.toLocaleString()} missing cells</span></div><button class="btn ghost" onclick="goToJourneyStep('start')">View / replace data</button>`;const values={profileRows:data.length.toLocaleString(),profileFields:headers.length,profileNumeric:numeric,profileMissing:miss.toLocaleString()};Object.entries(values).forEach(([id,v])=>{if(el(id))el(id).textContent=v})}
function fillRelationshipSelectors(){const a=el('relFieldA'),b=el('relFieldB');if(!a||!b||!loaded())return;const oldA=a.value,oldB=b.value,options=headers.map(h=>`<option value="${safe(h)}">${safe(h)} · ${safe(meta[h]?.level||types[h])}</option>`).join('');a.innerHTML=options;b.innerHTML=options;if(headers.includes(oldA))a.value=oldA;if(headers.includes(oldB))b.value=oldB;if(!a.value)a.value=headers[0];if(!b.value||b.value===a.value)b.value=headers.find(h=>h!==a.value)||headers[0];updateRelationshipMethod()}
function methodFor(a,b){const ka=fieldKind(a),kb=fieldKind(b);if(ka==='numeric'&&kb==='numeric')return{key:'numeric',title:'Numeric ↔ Numeric',desc:'Use Pearson for linear association or Spearman for monotonic/rank association.'};if(ka==='categorical'&&kb==='categorical')return{key:'categorical',title:'Categorical ↔ Categorical',desc:'Use a Chi-square test of independence and Cramér’s V effect size.'};return{key:'mixed',title:'Numeric ↔ Categorical',desc:'Compare group summaries and quantify group separation with η² (eta squared).'}}
function updateRelationshipMethod(){const a=el('relFieldA')?.value,b=el('relFieldB')?.value,host=el('relationshipMethod');if(!a||!b||!host)return;const m=methodFor(a,b);host.innerHTML=`<b>${m.title}</b><br>${m.desc}${m.key==='numeric'?` <select id="numericRelMethod" class="pill-select"><option value="pearson">Pearson</option><option value="spearman">Spearman</option></select>`:''}`}
function pairRows(a,b){const rows=[];for(const r of data){const x=r[a],y=r[b];if(x===''||x===null||x===undefined||y===''||y===null||y===undefined)continue;rows.push([x,y])}return rows}
function corrP(r,n){if(!Number.isFinite(r)||n<3||typeof jStat==='undefined')return NaN;if(Math.abs(r)>=1)return 0;const t=Math.abs(r)*Math.sqrt((n-2)/(1-r*r));return 2*(1-jStat.studentt.cdf(t,n-2))}
function strength(v){if(!Number.isFinite(v))return '—';if(v>=.7)return 'Strong';if(v>=.4)return 'Moderate';if(v>=.2)return 'Weak';return 'Very weak'}
function direction(v){if(!Number.isFinite(v))return 'Association could not be estimated.';if(Math.abs(v)<.05)return 'Little directional association was observed.';return `${v>0?'Positive':'Negative'} ${strength(Math.abs(v)).toLowerCase()}`}
function runNumeric(rows){const xs=rows.map(r=>Number(r[0])),ys=rows.map(r=>Number(r[1]));if(xs.some(v=>!Number.isFinite(v))||ys.some(v=>!Number.isFinite(v)))throw Error('Selected numeric fields contain non-numeric observed values.');const method=el('numericRelMethod')?.value||'pearson',r=stats().correlation(xs,ys,method),p=corrP(r,xs.length);return `<div class="rel-metrics"><div class="rel-metric"><b>${fmt(r)}</b><span>${method==='spearman'?'Spearman ρ':'Pearson r'}</span></div><div class="rel-metric"><b>${xs.length}</b><span>Complete pairs</span></div><div class="rel-metric"><b>${Number.isFinite(p)?(p<.001?'&lt;.001':fmt(p,4)):'—'}</b><span>Approx. p-value</span></div><div class="rel-metric"><b>${strength(Math.abs(r))}</b><span>Magnitude</span></div></div><div class="rel-note">${direction(r)} ${method==='spearman'?'rank/monotonic':'linear'} association. This is descriptive association and does not establish causation.</div>`}
function runCategorical(rows){const r=stats().chiSquareCramersV(rows);if(!Number.isFinite(r.chiSquare))throw Error('Both categorical fields need at least two observed levels.');const p=typeof jStat!=='undefined'?1-jStat.chisquare.cdf(r.chiSquare,r.df):NaN;return `<div class="rel-metrics"><div class="rel-metric"><b>${fmt(r.chiSquare)}</b><span>Chi-square</span></div><div class="rel-metric"><b>${r.df}</b><span>df</span></div><div class="rel-metric"><b>${Number.isFinite(p)?(p<.001?'&lt;.001':fmt(p,4)):'—'}</b><span>p-value</span></div><div class="rel-metric"><b>${fmt(r.cramersV)}</b><span>Cramér’s V</span></div></div><div class="rel-note">Cramér’s V summarizes association strength between these categorical fields. The Chi-square p-value addresses evidence against independence; neither measure implies causation.</div>`}
function runMixed(a,b,rows){const num=fieldKind(a)==='numeric'?a:b,cat=num===a?b:a,values=rows.map(r=>Number(num===a?r[0]:r[1])),groups=rows.map(r=>String(cat===a?r[0]:r[1])),r=stats().etaSquaredByGroup(values,groups);if(!Number.isFinite(r.etaSquared))throw Error('Mixed-type analysis needs at least two groups and three complete observations.');const rowsHtml=r.groups.sort((x,y)=>x.group.localeCompare(y.group)).slice(0,30).map(g=>`<tr><td>${safe(g.group)}</td><td>${g.n}</td><td>${fmt(g.mean)}</td></tr>`).join('');return `<div class="rel-metrics"><div class="rel-metric"><b>${fmt(r.etaSquared)}</b><span>η² (eta squared)</span></div><div class="rel-metric"><b>${r.groups.length}</b><span>Groups</span></div><div class="rel-metric"><b>${r.n}</b><span>Complete observations</span></div><div class="rel-metric"><b>${fmt(r.grandMean)}</b><span>Overall mean</span></div></div><div class="group-table"><table><thead><tr><th>${safe(cat)}</th><th>N</th><th>Mean ${safe(num)}</th></tr></thead><tbody>${rowsHtml}</tbody></table></div><div class="rel-note">η² is the proportion of observed variance in <b>${safe(num)}</b> accounted for by differences between groups of <b>${safe(cat)}</b>.${r.groups.length>30?' Only the first 30 groups are shown in the table.':''}</div>`}
function runRelationship(){const out=el('relationshipResult'),a=el('relFieldA')?.value,b=el('relFieldB')?.value;if(!out||!a||!b)return;if(a===b){out.innerHTML='<div class="advisor">Choose two different fields.</div>';return}try{if(!stats())throw Error('Relationship statistics module is unavailable.');const rows=pairRows(a,b);if(rows.length<3)throw Error('At least three complete paired observations are required.');const m=methodFor(a,b);out.innerHTML=m.key==='numeric'?runNumeric(rows):m.key==='categorical'?runCategorical(rows):runMixed(a,b,rows)}catch(err){out.innerHTML=`<div class="advisor"><b>Relationship could not be estimated.</b><br>${safe(err.message)}</div>`}}
function renderProductionProfile(){updateStart();if(!loaded())return;renderProfileHeader();renderOverview();renderQuality();fillRelationshipSelectors()}
function setProfileTab(name){document.querySelectorAll('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.profileTab===name));document.querySelectorAll('.profile-pane').forEach(p=>p.classList.toggle('active',p.dataset.profilePane===name));if(name==='relationships')fillRelationshipSelectors()}
window.renderProductionProfile=renderProductionProfile;window.setProfileTab=setProfileTab;window.runProfileRelationship=runRelationship;window.updateProfileRelationshipMethod=updateRelationshipMethod;
document.addEventListener('DOMContentLoaded',()=>{const status=el('status');if(status&&typeof MutationObserver!=='undefined')new MutationObserver(renderProductionProfile).observe(status,{childList:true,subtree:true,characterData:true});el('variableTable')?.addEventListener('change',()=>setTimeout(renderProductionProfile,0));renderProductionProfile()});
})();
