// KU Open DA — pure relationship statistics used by Data Profile.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KURelationshipStats=api;})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
function pearson(x,y){const n=x.length;if(n!==y.length||n<3)return NaN;const mx=x.reduce((s,v)=>s+v,0)/n,my=y.reduce((s,v)=>s+v,0)/n;let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const a=x[i]-mx,b=y[i]-my;num+=a*b;dx+=a*a;dy+=b*b}return dx&&dy?num/Math.sqrt(dx*dy):NaN}
function ranks(values){const sorted=values.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),out=Array(values.length);let i=0;while(i<sorted.length){let j=i+1;while(j<sorted.length&&sorted[j].v===sorted[i].v)j++;const rank=(i+j+1)/2;for(let k=i;k<j;k++)out[sorted[k].i]=rank;i=j}return out}
function correlation(x,y,method='pearson'){return method==='spearman'?pearson(ranks(x),ranks(y)):pearson(x,y)}
function chiSquareCramersV(pairs){const rowLevels=[...new Set(pairs.map(r=>String(r[0])))],colLevels=[...new Set(pairs.map(r=>String(r[1])))];if(rowLevels.length<2||colLevels.length<2)return{chiSquare:NaN,df:0,cramersV:NaN,n:pairs.length,rowLevels,colLevels};const ri=new Map(rowLevels.map((v,i)=>[v,i])),ci=new Map(colLevels.map((v,i)=>[v,i])),observed=Array.from({length:rowLevels.length},()=>Array(colLevels.length).fill(0)),rowTotals=Array(rowLevels.length).fill(0),colTotals=Array(colLevels.length).fill(0);for(const [a,b] of pairs){const i=ri.get(String(a)),j=ci.get(String(b));observed[i][j]++;rowTotals[i]++;colTotals[j]++}let chiSquare=0;for(let i=0;i<rowLevels.length;i++)for(let j=0;j<colLevels.length;j++){const expected=rowTotals[i]*colTotals[j]/pairs.length;if(expected>0)chiSquare+=(observed[i][j]-expected)**2/expected}const df=(rowLevels.length-1)*(colLevels.length-1),den=Math.min(rowLevels.length-1,colLevels.length-1),cramersV=den>0?Math.sqrt(chiSquare/(pairs.length*den)):NaN;return{chiSquare,df,cramersV,n:pairs.length,rowLevels,colLevels,observed,rowTotals,colTotals}}
function etaSquaredByGroup(values,groups){if(values.length!==groups.length||values.length<3)return{etaSquared:NaN,n:values.length,groups:[]};const grouped=new Map();for(let i=0;i<values.length;i++){const v=values[i],g=String(groups[i]);if(!Number.isFinite(v))continue;if(!grouped.has(g))grouped.set(g,[]);grouped.get(g).push(v)}const all=[...grouped.values()].flat();if(all.length<3||grouped.size<2)return{etaSquared:NaN,n:all.length,groups:[]};const grandMean=all.reduce((s,v)=>s+v,0)/all.length;let ssBetween=0,ssTotal=0;const summaries=[];for(const [group,vals] of grouped){const mean=vals.reduce((s,v)=>s+v,0)/vals.length;ssBetween+=vals.length*(mean-grandMean)**2;summaries.push({group,n:vals.length,mean})}for(const v of all)ssTotal+=(v-grandMean)**2;return{etaSquared:ssTotal>0?ssBetween/ssTotal:NaN,n:all.length,grandMean,groups:summaries,ssBetween,ssTotal}}
return{pearson,ranks,correlation,chiSquareCramersV,etaSquaredByGroup};
});
